// Opt-in integration tests for this app's renderer. Never uses player's profile.
const fs=require('node:fs/promises'),path=require('node:path'),assert=require('node:assert/strict'),{once}=require('node:events');
function wav(data,rate){const b=Buffer.alloc(44+data.length*2);b.write('RIFF');b.writeUInt32LE(b.length-8,4);b.write('WAVEfmt ',8);b.writeUInt32LE(16,16);b.writeUInt16LE(1,20);b.writeUInt16LE(1,22);b.writeUInt32LE(rate,24);b.writeUInt32LE(rate*2,28);b.writeUInt16LE(2,32);b.writeUInt16LE(16,34);b.write('data',36);b.writeUInt32LE(data.length*2,40);data.forEach((v,i)=>b.writeInt16LE(Math.round(Math.max(-1,Math.min(1,v))*32767),44+i*2));return b;}
module.exports=async(win,root)=>{
 const out=require('electron').app.isPackaged?path.join(path.dirname(process.execPath),'verification'):path.join(root,'verification','v1.1');await fs.mkdir(out,{recursive:true});const checks=[],errors=[];win.webContents.on('console-message',(event)=>{if(event.level==='error')errors.push(event.message);});
 const js=code=>win.webContents.executeJavaScript(`(async()=>{${code}})()`,true);
 const check=(name,value)=>{assert(value,name);checks.push(name);};
 const reload=async()=>{const loaded=once(win.webContents,'did-finish-load');win.webContents.reload();await loaded;};
 const idle=()=>js(`const deadline=Date.now()+8000;while(document.querySelector('#app').getAttribute('aria-busy')==='true'){if(Date.now()>deadline)throw Error('Animation input lock did not release');await new Promise(r=>setTimeout(r,50));}`);
 const click=async selector=>{await js(`const el=document.querySelector(${JSON.stringify(selector)});if(!el||el.disabled)throw Error('Missing control '+${JSON.stringify(selector)});el.dispatchEvent(new MouseEvent('click',{bubbles:true}));await new Promise(r=>setTimeout(r,60));`);await idle();};
 const snapshot=()=>js(`return JSON.parse(localStorage.getItem('emberbound.run.v1'));`);
 const screenshot=async name=>{await js(`await Promise.all([...document.images].map(i=>i.decode().catch(()=>{})));await new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r)));`);await fs.writeFile(path.join(out,name+'.png'),(await win.webContents.capturePage()).toPNG());};
 const toMenu=()=>js(`const pause=document.querySelector('[data-action="pause"]');if(pause){pause.click();document.querySelector('[data-action="menu"]').click();}`);
 const fixture=async code=>{await toMenu();await js(`const s=Engine.newRun('knight','DESKTOP-QA','story');${code}Engine.validate(s);localStorage.setItem('emberbound.run.v1',Engine.serialize(s));`);await reload();await click('[data-action="continue"]');};
 await js(`localStorage.clear();`);await reload();check('offline custom protocol and no Node in renderer',await js(`return location.protocol==='emberbound:'&&typeof require==='undefined'&&typeof process==='undefined';`));
 await screenshot('desktop-title');await click('[data-action="select"]');await click('[data-action="difficulty"][data-id="story"]');await click('[data-action="start"]');check('new run created through UI',(await snapshot()).phase==='map');
 const opening=await js(`document.querySelector('[data-action="node"]').dispatchEvent(new MouseEvent('click',{bubbles:true}));await new Promise(r=>setTimeout(r,60));return {count:document.querySelectorAll('.draw-flight').length,busy:document.querySelector('#app').getAttribute('aria-busy')};`);check('opening draw flies from pile with locked input',opening.count===5&&opening.busy==='true');await screenshot('opening-draw');await idle();check('route enters combat',(await snapshot()).phase==='combat');await screenshot('desktop-battle');
 check('all visible images load',await js(`return [...document.images].every(i=>i.complete&&i.naturalWidth>0);`));
 await fixture(`Engine.startBattle(s,'battle',['golem']);if(!s.combat.hand.some(c=>c.id==='cut')){const c=s.deck.find(c=>c.id==='cut');s.combat.draw=s.combat.draw.filter(x=>x.uid!==c.uid);s.combat.hand.push({...c});}`);
 const before=await snapshot();const lock=await js(`const el=document.querySelector('[data-action="play"][data-card-id="cut"]');el.click();el.click();document.dispatchEvent(new KeyboardEvent('keydown',{code:'Space',key:' '}));await new Promise(r=>setTimeout(r,40));return {busy:document.querySelector('#app').getAttribute('aria-busy'),flying:!!document.querySelector('.flying-card')};`);check('action locked while VFX active',lock.busy==='true'&&lock.flying);
 await new Promise(r=>setTimeout(r,350));await screenshot('attack-animation');await idle();const after=await snapshot();check('double-click and space during animation do not double-resolve',after.stats.cardsPlayed===before.stats.cardsPlayed+1&&after.combat.turn===before.combat.turn);check('one attack damage applied',after.combat.enemies[0].hp===before.combat.enemies[0].hp-6);
 await click('[data-action="endTurn"]');await new Promise(r=>setTimeout(r,1500));check('enemy turn unlocks normally',await js(`return document.querySelector('#app').getAttribute('aria-busy')==='false';`));check('new hand and next turn',(await snapshot()).combat.turn===2);
 const awaitElement=selector=>js(`const deadline=Date.now()+7000;while(!document.querySelector(${JSON.stringify(selector)})){if(Date.now()>deadline)throw Error('No animation '+${JSON.stringify(selector)});await new Promise(r=>setTimeout(r,15));}return true;`);
 await fixture(`Engine.startBattle(s,'battle',['golem']);Engine.drawCards(s,100);`);const shuffleBefore=await snapshot();
 const discarding=await js(`globalThis.qaMotions=[];globalThis.qaObserver=new MutationObserver(records=>{for(const r of records)for(const n of r.addedNodes)if(n.nodeType===1&&n.matches('.pile-flight'))qaMotions.push(n.className);});qaObserver.observe(document.body,{childList:true});document.querySelector('[data-action="endTurn"]').click();await new Promise(r=>setTimeout(r,40));return document.querySelectorAll('.discard-flight').length;`);check('end turn animates all ten discarded cards',discarding===10);await screenshot('discard-animation');
 await idle();const motions=await js(`qaObserver.disconnect();return qaMotions;`);check('empty draw pile visibly reshuffles',motions.some(x=>x.includes('shuffle-flight')));check('next turn draws five flying cards',motions.filter(x=>x.includes('draw-flight')).length===5);const reshuffled=await snapshot();check('reshuffle animations preserve rules and pile totals',reshuffled.combat.turn===shuffleBefore.combat.turn+1&&['hand','draw','discard','exhaust'].reduce((n,k)=>n+reshuffled.combat[k].length,0)===reshuffled.deck.length);
 await fixture(`Engine.addCard(s,'focus');Engine.startBattle(s,'battle',['golem']);const c=s.deck.find(c=>c.id==='focus');if(!s.combat.hand.some(x=>x.uid===c.uid)){s.combat.draw=s.combat.draw.filter(x=>x.uid!==c.uid);s.combat.hand.push({...c});}`);
 await js(`document.querySelector('[data-action="play"][data-card-id="focus"]').click();`);await awaitElement('.exhaust-flight');check('exhaust card visibly flies to exhaust pile',true);await screenshot('exhaust-animation');await idle();check('exhaust card never enters discard',(await snapshot()).combat.exhaust.some(c=>c.id==='focus'));
 await fixture(`s.phase='rest';`);await click('[data-action="rest"][data-id="upgrade"]');const picker=JSON.stringify(await snapshot());await click('[data-action="chooseCard"]');
 check('upgrade preview does not mutate save',JSON.stringify(await snapshot())===picker);check('both card faces and changed numbers visible',await js(`return document.querySelectorAll('.upgrade-comparison .card').length===2&&document.querySelector('.upgrade-diff').innerText.includes('9');`));await screenshot('upgrade-preview');
 await click('[data-action="close"]');check('cancel comparison leaves save identical',JSON.stringify(await snapshot())===picker);await click('[data-action="chooseCard"]');await click('[data-action="confirmUpgrade"]');const upgraded=await snapshot();check('confirmation upgrades exactly one and leaves rest',upgraded.deck.filter(c=>c.up).length===1&&upgraded.phase==='map');
 await reload();await click('[data-action="continue"]');check('desktop reload preserves upgraded run',JSON.stringify(await snapshot())===JSON.stringify(upgraded));await click('[data-action="deck"]');await click('[data-action="inspect"]');check('deck inspection has upgrade comparison',await js(`return document.querySelectorAll('.upgrade-comparison .card').length===2;`));await click('[data-action="inspectBack"]');check('inspection back returns to deck',await js(`return !!document.querySelector('.deck-grid');`));await click('[data-action="close"]');
 await click('[data-action="settings"]');await click('[data-action="testAudio"]');await new Promise(r=>setTimeout(r,200));check('live audio context running and voices scheduled',await js(`const a=Audio.audioState();return a.state==='running'&&a.voices>0&&a.volume>0;`));await screenshot('audio-settings');
 const audio=[];
 for(const kind of ['hit','spell','block','card','heal','win','lose','combo','click','music']){
  const r=await js(`const ctx=new OfflineAudioContext(1,22050*${kind==='music'?17:3},22050),g=ctx.createGain();g.gain.value=.55;g.connect(ctx.destination);${kind==='music'?"for(let i=0;i<32;i++)Audio.renderMusicBeat(ctx,g,i,i*.48);":`Audio.renderTone(ctx,g,${JSON.stringify(kind)},.01);`}const buf=await ctx.startRendering(),data=buf.getChannelData(0);let peak=0,sum=0;for(const v of data){peak=Math.max(peak,Math.abs(v));sum+=v*v;}return {kind:${JSON.stringify(kind)},peak,rms:Math.sqrt(sum/data.length),pcm:${['hit','music'].includes(kind)?'Array.from(data)':'null'},rate:buf.sampleRate};`);
  check(kind+' produces finite non-silent non-clipping audio',Number.isFinite(r.rms)&&r.rms>.003&&r.peak<1&&r.peak>.02);if(r.pcm)await fs.writeFile(path.join(out,kind+'-sample.wav'),wav(r.pcm,r.rate));delete r.pcm;audio.push(r);
 }
 await click('[data-action="close"]');await click('[data-action="catalog"]');check('all 56 available without collecting cards',await js(`await Promise.all([...document.images].map(i=>i.decode().catch(()=>{})));const imgs=[...document.querySelectorAll('.catalog-grid .card-art')];return imgs.length===56&&new Set(imgs.map(i=>i.src)).size===56&&imgs.every(i=>i.naturalWidth>0);`));await screenshot('card-gallery');
 await js(`const el=document.querySelector('[data-catalog="hero"]');el.value='mage';el.dispatchEvent(new Event('change',{bubbles:true}));`);check('catalog class filter',await js(`return document.querySelectorAll('.catalog-grid .card').length===16;`));await click('[data-action="resetCatalog"]');
 await js(`const el=document.querySelector('[data-catalog="query"]');el.value='中毒';el.dispatchEvent(new Event('input',{bubbles:true}));await new Promise(r=>setTimeout(r,30));return true;`);check('search by effects maintains input focus',await js(`return document.querySelectorAll('.catalog-grid .card').length>0&&document.activeElement.dataset.catalog==='query';`));await click('[data-action="resetCatalog"]');await click('[data-action="inspect"]');await click('[data-action="inspectBack"]');check('inspection returns to catalog',await js(`return !!document.querySelector('.catalog-grid');`));
 await click('[data-action="close"]');await fixture(`Engine.startBattle(s,'battle',['wolf']);`);win.setContentSize(1280,720);await new Promise(r=>setTimeout(r,100));check('1280x720 combat fits with illustrations',await js(`return document.documentElement.scrollWidth<=innerWidth&&document.documentElement.scrollHeight<=innerHeight;`));await screenshot('battle-720p');
 await click('[data-action="catalog"]');await js(`const el=document.querySelector('[data-catalog="up"]');el.checked=true;el.dispatchEvent(new Event('change',{bubbles:true}));`);check('catalog upgrade toggle shows all playable upgraded cards',await js(`return document.querySelectorAll('.catalog-grid .card.upgraded').length===54;`));await click('[data-action="close"]');
 await click('[data-action="settings"]');await click('[data-action="toggleMotion"]');await click('[data-action="close"]');await click('[data-action="play"]');await new Promise(r=>setTimeout(r,180));check('reduced-motion mode resolves without stuck input',await js(`return document.querySelector('#app').getAttribute('aria-busy')==='false';`));
 check('no renderer errors',errors.length===0);
 const report={date:new Date().toISOString(),electron:process.versions.electron,chromium:process.versions.chrome,packaged:require('electron').app.isPackaged,checks,audio,errors,notes:['Opt-in isolated-profile integration harness; fixture states are developer tests, not claimed as organic playthrough.','PCM output and running context verified; human listening not claimed.']};
 await fs.writeFile(path.join(out,require('electron').app.isPackaged?'packaged-report.json':'desktop-report.json'),JSON.stringify(report,null,2));console.log(JSON.stringify({passed:checks.length,out,audio:audio.map(x=>({kind:x.kind,rms:x.rms}))}));
};
